namespace Analyser.Lexical
{
    public enum TokenTypeEnum
    {
        Undefined = -2,
        Eof = -1,
        Main = 0,
        OpenParentheses = 1,
        CloseParentheses = 2,
        OpenKeys = 3,
        CloseKeys = 4,
        TypeInt = 5,
        TypeChar = 6,
        TypeReal = 7,
        Identifier = 8,
        Comma = 9,
        Semicolon = 10,
        Assignment = 13,
        OperatorPotentiation = 14,
        OperatorSum = 15,
        OperatorSubtraction = 16,
        OperatorMultiplication = 17,
        OperatorDivision = 18,
        OperatorEquals = 19,
        OperatorLessEquals = 20,
        OperatorGreaterEquals = 21,
        OperatorBigger = 22,
        OperatorSmaller = 23,
        Space = 24,
        Tab = 25,
        LineBreak = 26,
        OpenBrackets = 27,
        CloseBrackets = 28,
        Dot = 29,
        ReservedWordVar = 30,
        ReservedWordWhile = 31,
        ReservedWordFor = 32,
        ReservedWordIf = 33,
        ReservedWordElse = 34,
        ReservedWordSwitch = 35,
        ReservedWordCase = 36,
        ReservedWordReturn = 37,
        ReservedWordFunction = 39,
        Number = 40,
        Real = 41,
        Char = 42
    }
}